#!/bin/bash
# ==============================================================
# job_recovery.sh — Login-node orchestrator
#
# Reads a recovery plan generated by job_audit.sh and submits
# the appropriate SLURM jobs with correct resource profiles
# and dependency chains. Submits a final audit at the end.
#
# Run from the login node:  bash job_recovery.sh
# ==============================================================

set -euo pipefail

# --- User-configurable variables ---
EXPERIMENT="alexnet_cifar10"
TOTAL_CHUNKS=8
BATCH_SIZE=1800
NUM_SAMPLES_PER_CLASS=100
SAMPLES_PER_ATTACK=500
ACCOUNT="def-assem"

# --- Paths ---
PLAN_FILE="experiments/$EXPERIMENT/recovery_plan.sh"
RECOVERY_DIR="experiments/$EXPERIMENT/recovery_jobs"

if [ ! -f "$PLAN_FILE" ]; then
    echo "ERROR: Recovery plan not found: $PLAN_FILE"
    echo "Run job_audit.sh first to generate a recovery plan."
    exit 1
fi

# --- Load recovery plan ---
source "$PLAN_FILE"

if [ "$RECOVERY_NEEDED" = "false" ]; then
    echo "No recovery needed — all artifacts OK."
    exit 0
fi

echo "=============================================================="
echo "  Recovery for experiment: $EXPERIMENT"
echo "  Plan generated at: $RECOVERY_GENERATED_AT"
echo "=============================================================="

# --- Create recovery_jobs directory ---
mkdir -p "$RECOVERY_DIR"
mkdir -p slurm_out slurm_err

# --- Helper: submit and capture job ID ---
submit_job() {
    local script="$1"
    local deps="$2"
    local sbatch_cmd="sbatch"
    if [ -n "$deps" ]; then
        sbatch_cmd="sbatch --dependency=afterok:${deps}"
    fi
    local output
    output=$($sbatch_cmd "$script")
    local job_id
    job_id=$(echo "$output" | awk '{print $NF}')
    echo "$job_id"
}

# Track job IDs for dependency chain
JOB_A=""
JOB_B_IDS=""
JOB_C=""
JOB_D_IDS=""
JOB_E=""
JOB_F_IDS=""
JOB_G=""
ALL_JOBS=""

# ==============================================================
# Step A: Training
# ==============================================================
if [ "$RECOVER_STEP_A" = "true" ]; then
    cat > "$RECOVERY_DIR/step_A.sh" << 'STEPA_EOF'
#!/bin/bash
#SBATCH --account=ACCOUNT_PLACEHOLDER
#SBATCH --gpus=a100_2g.10gb:1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:30:00
#SBATCH --mem=31G
#SBATCH --output=slurm_out/REC_A_train_%A.out
#SBATCH --error=slurm_err/REC_A_train_%A.err

mkdir -p $SLURM_SUBMIT_DIR/slurm_out
mkdir -p $SLURM_SUBMIT_DIR/slurm_err

module load StdEnv/2023 python/3.11.5 scipy-stack/2025a
source env_rorqual/bin/activate

EXPERIMENT="EXPERIMENT_PLACEHOLDER"

mkdir -p $SLURM_TMPDIR/data/cifar-10-batches-py/
cp -r data/cifar-10-batches-py/* $SLURM_TMPDIR/data/cifar-10-batches-py/ 2>/dev/null || true
mkdir -p $SLURM_TMPDIR/data/cifar-100-python/
cp -r data/cifar-100-python/* $SLURM_TMPDIR/data/cifar-100-python/ 2>/dev/null || true
mkdir -p $SLURM_TMPDIR/data/ILSVRC2012/
cp -r /datashare/imagenet/ILSVRC2012/* $SLURM_TMPDIR/data/ILSVRC2012/ 2>/dev/null || true

python training.py --experiment_name $EXPERIMENT --temp_dir $SLURM_TMPDIR
echo "Step A (training) complete."
STEPA_EOF

    sed -i "s/ACCOUNT_PLACEHOLDER/$ACCOUNT/g" "$RECOVERY_DIR/step_A.sh"
    sed -i "s/EXPERIMENT_PLACEHOLDER/$EXPERIMENT/g" "$RECOVERY_DIR/step_A.sh"

    JOB_A=$(submit_job "$RECOVERY_DIR/step_A.sh" "")
    ALL_JOBS="$JOB_A"
    echo "[Step A] Training submitted: Job $JOB_A"
fi

# ==============================================================
# Step B: Generate matrices (per chunk)
# ==============================================================
if [ "$RECOVER_STEP_B" = "true" ]; then
    for CHUNK in $RECOVER_STEP_B_CHUNKS; do
        cat > "$RECOVERY_DIR/step_B_chunk_${CHUNK}.sh" << STEPB_EOF
#!/bin/bash
#SBATCH --account=$ACCOUNT
#SBATCH --gpus=h100:1
#SBATCH --cpus-per-task=12
#SBATCH --time=00:20:00
#SBATCH --mem=280G
#SBATCH --output=slurm_out/REC_B_mats_${CHUNK}_%A.out
#SBATCH --error=slurm_err/REC_B_mats_${CHUNK}_%A.err

mkdir -p \$SLURM_SUBMIT_DIR/slurm_out
mkdir -p \$SLURM_SUBMIT_DIR/slurm_err

module load StdEnv/2023 python/3.11.5 scipy-stack/2025a
source env_rorqual/bin/activate

EXPERIMENT="$EXPERIMENT"
TASK_ID=$CHUNK
TEMP_DIR=\$SLURM_TMPDIR
ZIP_FILE=\$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/matrices_task_\$TASK_ID.zip

mkdir -p \$SLURM_TMPDIR/data/cifar-10-batches-py/
cp -r data/cifar-10-batches-py/* \$SLURM_TMPDIR/data/cifar-10-batches-py/ 2>/dev/null || true
mkdir -p \$SLURM_TMPDIR/data/cifar-100-python/
cp -r data/cifar-100-python/* \$SLURM_TMPDIR/data/cifar-100-python/ 2>/dev/null || true

mkdir -p \$TEMP_DIR/experiments/\$EXPERIMENT/weights/
cp experiments/\$EXPERIMENT/weights/* \$TEMP_DIR/experiments/\$EXPERIMENT/weights/

if [ -f "\$ZIP_FILE" ]; then
    cp "\$ZIP_FILE" "\$TEMP_DIR/experiments/\$EXPERIMENT/"
    unzip -o "\$TEMP_DIR/experiments/\$EXPERIMENT/matrices_task_\$TASK_ID.zip" -d "\$TEMP_DIR/experiments/\$EXPERIMENT/"
fi

timeout 20m python generate_matrices.py --temp_dir \$TEMP_DIR --experiment \$EXPERIMENT --chunk_id \$TASK_ID --total_chunks $TOTAL_CHUNKS --batch_size $BATCH_SIZE --num_samples_per_class $NUM_SAMPLES_PER_CLASS

cd \$TEMP_DIR/experiments/\$EXPERIMENT
zip -r matrices_task_\$TASK_ID.zip matrices || { echo "Zipping failed"; exit 1; }

cd \$SLURM_SUBMIT_DIR
python -m utils.data_integrity --verify-zip \$TEMP_DIR/experiments/\$EXPERIMENT/matrices_task_\$TASK_ID.zip || { echo "Zip verification failed"; exit 1; }

cp \$TEMP_DIR/experiments/\$EXPERIMENT/matrices_task_\$TASK_ID.zip \$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/ || { echo "Failed to copy zip"; exit 1; }
echo "Step B chunk $CHUNK complete."
STEPB_EOF

        DEP=""
        if [ -n "$JOB_A" ]; then
            DEP="$JOB_A"
        fi
        JOB_ID=$(submit_job "$RECOVERY_DIR/step_B_chunk_${CHUNK}.sh" "$DEP")
        JOB_B_IDS="${JOB_B_IDS:+$JOB_B_IDS:}$JOB_ID"
        ALL_JOBS="${ALL_JOBS:+$ALL_JOBS:}$JOB_ID"
        echo "[Step B] Matrices chunk $CHUNK submitted: Job $JOB_ID (depends on: ${DEP:-none})"
    done
fi

# ==============================================================
# Step C: Adversarial examples
# ==============================================================
if [ "$RECOVER_STEP_C" = "true" ]; then
    cat > "$RECOVERY_DIR/step_C.sh" << STEPC_EOF
#!/bin/bash
#SBATCH --account=$ACCOUNT
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=16
#SBATCH --time=04:00:00
#SBATCH --mem=124G
#SBATCH --output=slurm_out/REC_C_adv_ex_%A.out
#SBATCH --error=slurm_err/REC_C_adv_ex_%A.err

mkdir -p \$SLURM_SUBMIT_DIR/slurm_out
mkdir -p \$SLURM_SUBMIT_DIR/slurm_err

module load StdEnv/2023 python/3.11.5 scipy-stack/2025a
source env_rorqual/bin/activate

EXPERIMENT="$EXPERIMENT"

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/weights/
cp experiments/\$EXPERIMENT/weights/* \$SLURM_TMPDIR/experiments/\$EXPERIMENT/weights/

mkdir -p \$SLURM_TMPDIR/data/cifar-10-batches-py/
cp -r data/cifar-10-batches-py/* \$SLURM_TMPDIR/data/cifar-10-batches-py/ 2>/dev/null || true
mkdir -p \$SLURM_TMPDIR/data/cifar-100-python/
cp -r data/cifar-100-python/* \$SLURM_TMPDIR/data/cifar-100-python/ 2>/dev/null || true

python generate_adversarial_examples.py --experiment_name \$EXPERIMENT --temp_dir=\$SLURM_TMPDIR
echo "Step C (adversarial examples) complete."
STEPC_EOF

    DEP=""
    if [ -n "$JOB_A" ]; then
        DEP="$JOB_A"
    fi
    JOB_C=$(submit_job "$RECOVERY_DIR/step_C.sh" "$DEP")
    ALL_JOBS="${ALL_JOBS:+$ALL_JOBS:}$JOB_C"
    echo "[Step C] Adversarial examples submitted: Job $JOB_C (depends on: ${DEP:-none})"
fi

# ==============================================================
# Step D: Rejection level matrices (per chunk)
# ==============================================================
if [ "$RECOVER_STEP_D" = "true" ]; then
    for CHUNK in $RECOVER_STEP_D_CHUNKS; do
        cat > "$RECOVERY_DIR/step_D_chunk_${CHUNK}.sh" << STEPD_EOF
#!/bin/bash
#SBATCH --account=$ACCOUNT
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=16
#SBATCH --time=09:00:00
#SBATCH --mem=180G
#SBATCH --output=slurm_out/REC_D_rej_lev_${CHUNK}_%A.out
#SBATCH --error=slurm_err/REC_D_rej_lev_${CHUNK}_%A.err

mkdir -p \$SLURM_SUBMIT_DIR/slurm_out
mkdir -p \$SLURM_SUBMIT_DIR/slurm_err

module load StdEnv/2023 python/3.11.5 scipy-stack/2025a
source env_rorqual/bin/activate

EXPERIMENT="$EXPERIMENT"
TASK_ID=$CHUNK
ZIP_OUTPUT_FILE="matrices_task_\$TASK_ID.zip"

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/weights/
cp \$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/weights/* \$SLURM_TMPDIR/experiments/\$EXPERIMENT/weights/

mkdir -p \$SLURM_TMPDIR/data/cifar-10-batches-py/
cp -r data/cifar-10-batches-py/* \$SLURM_TMPDIR/data/cifar-10-batches-py/ 2>/dev/null || true
mkdir -p \$SLURM_TMPDIR/data/cifar-100-python/
cp -r data/cifar-100-python/* \$SLURM_TMPDIR/data/cifar-100-python/ 2>/dev/null || true

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/rejection_levels/

EXPERIMENT_DATA_TRAIN="\$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/rejection_levels/exp_dataset_train.pth"
EXPERIMENT_DATA_LABELS="\$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/rejection_levels/exp_dataset_labels.pth"
if [ -f "\$EXPERIMENT_DATA_TRAIN" ]; then
    cp "\$EXPERIMENT_DATA_TRAIN" "\$SLURM_TMPDIR/experiments/\$EXPERIMENT/rejection_levels/"
fi
if [ -f "\$EXPERIMENT_DATA_LABELS" ]; then
    cp "\$EXPERIMENT_DATA_LABELS" "\$SLURM_TMPDIR/experiments/\$EXPERIMENT/rejection_levels/"
fi

ZIP_FILE="\$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/rejection_levels/\$ZIP_OUTPUT_FILE"
if [ -f "\$ZIP_FILE" ]; then
    cp "\$ZIP_FILE" "\$SLURM_TMPDIR/experiments/\$EXPERIMENT/rejection_levels/"
    cd "\$SLURM_TMPDIR/experiments/\$EXPERIMENT/rejection_levels/"
    unzip -o "\$ZIP_OUTPUT_FILE"
    cd -
fi

timeout 8h python compute_matrices_for_rejection_level.py \
    --experiment_name \$EXPERIMENT \
    --temp_dir \$SLURM_TMPDIR \
    --batch_size $BATCH_SIZE \
    --chunk_id \$TASK_ID \
    --total_chunks $TOTAL_CHUNKS

MATRICES_DIR="\$SLURM_TMPDIR/experiments/\$EXPERIMENT/rejection_levels/matrices"
ZIP_OUTPUT_DIR="\$SLURM_TMPDIR/experiments/\$EXPERIMENT/rejection_levels"

if [ -d "\$MATRICES_DIR" ]; then
    cd "\$ZIP_OUTPUT_DIR"
    zip -r "\$ZIP_OUTPUT_FILE" matrices || { echo "Zip failed"; exit 1; }

    cd \$SLURM_SUBMIT_DIR
    python -m utils.data_integrity --verify-zip "\$ZIP_OUTPUT_DIR/\$ZIP_OUTPUT_FILE" || { echo "Zip verification failed"; exit 1; }
fi

DEST_DIR="\$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/rejection_levels/"
mkdir -p "\$DEST_DIR"
if [ -f "\$ZIP_OUTPUT_DIR/\$ZIP_OUTPUT_FILE" ]; then
    cp "\$ZIP_OUTPUT_DIR/\$ZIP_OUTPUT_FILE" "\$DEST_DIR" || { echo "Failed to copy zip"; exit 1; }
fi
echo "Step D chunk $CHUNK complete."
STEPD_EOF

        DEP=""
        if [ -n "$JOB_A" ]; then
            DEP="$JOB_A"
        fi
        JOB_ID=$(submit_job "$RECOVERY_DIR/step_D_chunk_${CHUNK}.sh" "$DEP")
        JOB_D_IDS="${JOB_D_IDS:+$JOB_D_IDS:}$JOB_ID"
        ALL_JOBS="${ALL_JOBS:+$ALL_JOBS:}$JOB_ID"
        echo "[Step D] Rejection level chunk $CHUNK submitted: Job $JOB_ID (depends on: ${DEP:-none})"
    done
fi

# ==============================================================
# Step E: Matrix statistics (depends on all B jobs)
# ==============================================================
if [ "$RECOVER_STEP_E" = "true" ]; then
    cat > "$RECOVERY_DIR/step_E.sh" << STEPE_EOF
#!/bin/bash
#SBATCH --account=$ACCOUNT
#SBATCH --cpus-per-task=2
#SBATCH --time=01:00:00
#SBATCH --mem-per-cpu=8G
#SBATCH --output=slurm_out/REC_E_mat_stats_%A.out
#SBATCH --error=slurm_err/REC_E_mat_stats_%A.err

mkdir -p \$SLURM_SUBMIT_DIR/slurm_out
mkdir -p \$SLURM_SUBMIT_DIR/slurm_err

module load StdEnv/2023 python/3.11.5 scipy-stack/2025a
source env_rorqual/bin/activate

EXPERIMENT="$EXPERIMENT"

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/matrices/

for i in \$(seq 0 $(( TOTAL_CHUNKS - 1 ))); do
    cp experiments/\$EXPERIMENT/matrices_task_\$i.zip \$SLURM_TMPDIR/experiments/\$EXPERIMENT/
    unzip "\$SLURM_TMPDIR/experiments/\$EXPERIMENT/matrices_task_\$i.zip" -d "\$SLURM_TMPDIR/experiments/\$EXPERIMENT/"
done

echo "Matrices unzipped. Computing statistics..."
python compute_matrix_statistics.py --experiment_name \$EXPERIMENT --temp_dir \$SLURM_TMPDIR
echo "Step E (matrix statistics) complete."
STEPE_EOF

    DEP=""
    if [ -n "$JOB_B_IDS" ]; then
        DEP="$JOB_B_IDS"
    fi
    JOB_E=$(submit_job "$RECOVERY_DIR/step_E.sh" "$DEP")
    ALL_JOBS="${ALL_JOBS:+$ALL_JOBS:}$JOB_E"
    echo "[Step E] Matrix statistics submitted: Job $JOB_E (depends on: ${DEP:-none})"
fi

# ==============================================================
# Step F: Adversarial matrices (per chunk, depends on C)
# ==============================================================
if [ "$RECOVER_STEP_F" = "true" ]; then
    for CHUNK in $RECOVER_STEP_F_CHUNKS; do
        cat > "$RECOVERY_DIR/step_F_chunk_${CHUNK}.sh" << STEPF_EOF
#!/bin/bash
#SBATCH --account=$ACCOUNT
#SBATCH --gpus=h100:1
#SBATCH --cpus-per-task=12
#SBATCH --time=12:00:00
#SBATCH --mem=280G
#SBATCH --output=slurm_out/REC_F_adv_mats_${CHUNK}_%A.out
#SBATCH --error=slurm_err/REC_F_adv_mats_${CHUNK}_%A.err

mkdir -p \$SLURM_SUBMIT_DIR/slurm_out
mkdir -p \$SLURM_SUBMIT_DIR/slurm_err

module load StdEnv/2023 python/3.11.5 scipy-stack/2025a
source env_rorqual/bin/activate

EXPERIMENT="$EXPERIMENT"
TASK_ID=$CHUNK
ZIP_FILE="\$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/adv_matrices_task_\$TASK_ID.zip"

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/weights/
cp \$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/weights/* \$SLURM_TMPDIR/experiments/\$EXPERIMENT/weights/

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adversarial_examples/
tar cf - -C \$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/adversarial_examples . | tar xf - -C \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adversarial_examples

if [ -f "\$ZIP_FILE" ]; then
    cp "\$ZIP_FILE" "\$SLURM_TMPDIR/experiments/\$EXPERIMENT/"
    unzip "\$SLURM_TMPDIR/experiments/\$EXPERIMENT/adv_matrices_task_\$TASK_ID.zip" -d "\$SLURM_TMPDIR/experiments/\$EXPERIMENT/"
fi

timeout 11h python generate_adversarial_matrices.py --experiment_name \$EXPERIMENT --temp_dir \$SLURM_TMPDIR --chunk_id \$TASK_ID --total_chunks $TOTAL_CHUNKS --batch_size $BATCH_SIZE --samples_per_attack $SAMPLES_PER_ATTACK

cd \$SLURM_TMPDIR/experiments/\$EXPERIMENT/
zip -r adv_matrices_task_\$TASK_ID.zip adversarial_matrices/ || { echo "Zipping failed"; exit 1; }

cd \$SLURM_SUBMIT_DIR
python -m utils.data_integrity --verify-zip \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adv_matrices_task_\$TASK_ID.zip || { echo "Zip verification failed"; exit 1; }

cp \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adv_matrices_task_\$TASK_ID.zip \$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/ || { echo "Failed to copy zip"; exit 1; }
echo "Step F chunk $CHUNK complete."
STEPF_EOF

        DEP=""
        if [ -n "$JOB_C" ]; then
            DEP="$JOB_C"
        fi
        JOB_ID=$(submit_job "$RECOVERY_DIR/step_F_chunk_${CHUNK}.sh" "$DEP")
        JOB_F_IDS="${JOB_F_IDS:+$JOB_F_IDS:}$JOB_ID"
        ALL_JOBS="${ALL_JOBS:+$ALL_JOBS:}$JOB_ID"
        echo "[Step F] Adversarial matrices chunk $CHUNK submitted: Job $JOB_ID (depends on: ${DEP:-none})"
    done
fi

# ==============================================================
# Step G: Grid search (depends on E + all F + all D)
# ==============================================================
if [ "$RECOVER_STEP_G" = "true" ]; then
    cat > "$RECOVERY_DIR/step_G.sh" << STEPG_EOF
#!/bin/bash
#SBATCH --account=$ACCOUNT
#SBATCH --cpus-per-task=64
#SBATCH --time=48:00:00
#SBATCH --mem-per-cpu=42G
#SBATCH --output=slurm_out/REC_G_grid_search_%A.out
#SBATCH --error=slurm_err/REC_G_grid_search_%A.err

mkdir -p \$SLURM_SUBMIT_DIR/slurm_out
mkdir -p \$SLURM_SUBMIT_DIR/slurm_err

module load StdEnv/2023 python/3.11.5 scipy-stack/2025a
source env_rorqual/bin/activate
export OMP_NUM_THREADS=\$SLURM_CPUS_PER_TASK

EXPERIMENT="$EXPERIMENT"

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/weights/
cp experiments/\$EXPERIMENT/weights/* \$SLURM_TMPDIR/experiments/\$EXPERIMENT/weights/

mkdir -p \$SLURM_TMPDIR/data/cifar-10-batches-py/
cp -r data/cifar-10-batches-py/* \$SLURM_TMPDIR/data/cifar-10-batches-py/ 2>/dev/null || true
mkdir -p \$SLURM_TMPDIR/data/cifar-100-python/
cp -r data/cifar-100-python/* \$SLURM_TMPDIR/data/cifar-100-python/ 2>/dev/null || true

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/matrices/
cp experiments/\$EXPERIMENT/matrices/matrix_statistics.json \$SLURM_TMPDIR/experiments/\$EXPERIMENT/matrices/

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adversarial_matrices/
for i in \$(seq 0 $(( TOTAL_CHUNKS - 1 ))); do
    cp experiments/\$EXPERIMENT/adv_matrices_task_\$i.zip \$SLURM_TMPDIR/experiments/\$EXPERIMENT/
    unzip \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adv_matrices_task_\$i.zip -d \$SLURM_TMPDIR/experiments/\$EXPERIMENT/
done

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adversarial_examples/
cp -r experiments/\$EXPERIMENT/adversarial_examples/* \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adversarial_examples/

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/rejection_levels/matrices/
cp -r experiments/\$EXPERIMENT/rejection_levels/* \$SLURM_TMPDIR/experiments/\$EXPERIMENT/rejection_levels/

for i in \$(seq 0 $(( TOTAL_CHUNKS - 1 ))); do
    if [ -f "\$SLURM_TMPDIR/experiments/\$EXPERIMENT/rejection_levels/matrices_task_\$i.zip" ]; then
        unzip \$SLURM_TMPDIR/experiments/\$EXPERIMENT/rejection_levels/matrices_task_\$i.zip -d \$SLURM_TMPDIR/experiments/\$EXPERIMENT/rejection_levels/
    fi
done

echo "All data ready. Starting grid search..."
python grid_search.py --nb_workers \$SLURM_CPUS_PER_TASK --experiment_name \$EXPERIMENT --temp_dir \$SLURM_TMPDIR --rej_lev 0
echo "Step G (grid search) complete."
STEPG_EOF

    # Build dependency: E + all F + all D
    G_DEPS=""
    if [ -n "$JOB_E" ]; then
        G_DEPS="$JOB_E"
    fi
    if [ -n "$JOB_F_IDS" ]; then
        G_DEPS="${G_DEPS:+$G_DEPS:}$JOB_F_IDS"
    fi
    if [ -n "$JOB_D_IDS" ]; then
        G_DEPS="${G_DEPS:+$G_DEPS:}$JOB_D_IDS"
    fi
    JOB_G=$(submit_job "$RECOVERY_DIR/step_G.sh" "$G_DEPS")
    ALL_JOBS="${ALL_JOBS:+$ALL_JOBS:}$JOB_G"
    echo "[Step G] Grid search submitted: Job $JOB_G (depends on: ${G_DEPS:-none})"
fi

# ==============================================================
# Final Audit: depends on all submitted jobs
# ==============================================================
cat > "$RECOVERY_DIR/final_audit.sh" << FINALAUDIT_EOF
#!/bin/bash
#SBATCH --account=$ACCOUNT
#SBATCH --time=02:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --output=slurm_out/REC_FINAL_AUDIT_%A.out
#SBATCH --error=slurm_err/REC_FINAL_AUDIT_%A.err

mkdir -p \$SLURM_SUBMIT_DIR/slurm_out
mkdir -p \$SLURM_SUBMIT_DIR/slurm_err

module load StdEnv/2023 python/3.11.5 scipy-stack/2025a
source env_rorqual/bin/activate

EXPERIMENT="$EXPERIMENT"
TOTAL_CHUNKS=$TOTAL_CHUNKS

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/
cp -r experiments/\$EXPERIMENT/* \$SLURM_TMPDIR/experiments/\$EXPERIMENT/

cd \$SLURM_SUBMIT_DIR

python << 'AUDIT_PY_EOF'
import sys, os, json
sys.path.insert(0, os.environ["SLURM_SUBMIT_DIR"])
from utils.data_integrity import verify_experiment, _print_report
from constants.constants import ATTACKS, DEFAULT_EXPERIMENTS

experiment = os.environ["EXPERIMENT"]
total_chunks = int(os.environ["TOTAL_CHUNKS"])
tmpdir = os.environ["SLURM_TMPDIR"]
experiment_dir = os.path.join(tmpdir, "experiments", experiment)

num_classes = 10
if experiment in DEFAULT_EXPERIMENTS:
    dataset = DEFAULT_EXPERIMENTS[experiment].get("dataset", "cifar10")
    if dataset == "cifar100": num_classes = 100
    elif dataset == "imagenet": num_classes = 1000

report = verify_experiment(
    experiment_dir=experiment_dir, experiment_name=experiment,
    num_classes=num_classes, num_samples_per_class=1000,
    total_chunks=total_chunks, num_samples_rejection_level=10000,
    attacks_list=ATTACKS, sample_ratio=1.0,
)
_print_report(report)

report_path = os.path.join(experiment_dir, "audit_report.json")
with open(report_path, "w") as f:
    json.dump(report, f, indent=2)
print(f"Post-recovery audit report saved to: {report_path}")
AUDIT_PY_EOF

cp \$SLURM_TMPDIR/experiments/\$EXPERIMENT/audit_report.json \
   \$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/audit_report.json
echo "Final audit complete."
FINALAUDIT_EOF

FINAL_AUDIT_JOB=$(submit_job "$RECOVERY_DIR/final_audit.sh" "$ALL_JOBS")
echo ""
echo "[Final Audit] Post-recovery audit submitted: Job $FINAL_AUDIT_JOB (depends on: $ALL_JOBS)"

# ==============================================================
# Summary
# ==============================================================
echo ""
echo "=============================================================="
echo "  Recovery jobs submitted for: $EXPERIMENT"
echo "=============================================================="
echo ""
echo "  Dependency chain:"
[ -n "$JOB_A" ]     && echo "    Step A (Training):            $JOB_A"
if [ -n "$JOB_B_IDS" ]; then
    echo "    Step B (Matrices):            ${JOB_B_IDS//:/, }"
fi
[ -n "$JOB_C" ]     && echo "    Step C (Adv examples):        $JOB_C"
if [ -n "$JOB_D_IDS" ]; then
    echo "    Step D (Rejection levels):    ${JOB_D_IDS//:/, }"
fi
[ -n "$JOB_E" ]     && echo "    Step E (Matrix statistics):   $JOB_E"
if [ -n "$JOB_F_IDS" ]; then
    echo "    Step F (Adv matrices):        ${JOB_F_IDS//:/, }"
fi
[ -n "$JOB_G" ]     && echo "    Step G (Grid search):         $JOB_G"
echo "    Final Audit:                  $FINAL_AUDIT_JOB"
echo ""
echo "  Monitor with: squeue -u \$USER"
echo "  Generated scripts: $RECOVERY_DIR/"
echo "=============================================================="
