"""Canonical (model, class, image) enumeration for the km-feature-viz experiment.

A single source of truth: every downstream script consumes this manifest
and verifies its hash. Hash mismatch on rsync → notebook refuses to render.

ImageNet layout: uses the same convention as other experiments in this repo
(theorem45, isomorphism, teleportation) — `get_imagenet_val_dataset` from
`utils/utils.py` auto-detects ImageFolder (synset subdirs) vs flat
ILSVRC2012_val_*.JPEG + ground-truth file. Default base path on nibi:
`/datashare/imagenet/ILSVRC2012`.

Pillar 3 framing — class & image budget
=======================================
The manifest below is sized for paper Pillar 3 ("Exact image-space attribution:
knowledge matrices as canonical saliency"). The figure budget targets a small,
qualitatively diverse set of classes rendered across multiple methods (KM rows,
DeepDream, Grad-CAM, IG, SmoothGrad, ...) across three ImageNet architectures
that span the dominant CNN family lines: ResNet152 (residual), DenseNet121
(dense connectivity), and GoogLeNet / InceptionV1 (multi-branch inception).

Why these three classes (207, 282, 340)?
- 207 = golden retriever — animal, single dominant subject, fine-grained dog class.
- 282 = tiger cat — the user's "one type of cat"; visually distinct from the dog
        class (different subject morphology, complementary visual statistics).
- 340 = zebra — high-contrast texture (stripes), distinct from the two mammals
        above; classic interp-paper class for testing whether saliency methods
        latch onto the diagnostic stripe pattern.

Three classes is the smallest set that lets us show *intra-class consistency*
(multiple images per class) and *inter-class contrast* in the same figure
without exceeding TMLR's plate budget.

Why 7 + 7 + 6 = 20 images?
- Total cap of 20 images per the figure budget for Pillar 3 (one model run
  produces 20 panels per method; with ~6 methods this is already ~120 panels).
- The +1 retriever bias (7 vs 6) reflects the user's preference: golden
  retriever is the headline class for the rendered figure, so it gets one
  extra exemplar to support a 4×2 grid in the main-text figure while leaving
  the cat and zebra columns at 7 / 6 for the appendix.

Why these three architectures?
- ResNet152 — deepest of the three; stresses the chunked-KM compute path the
  hardest. BatchNorm + residual connections produce the most interesting KM
  decomposition signal to compare against the saliency baselines.
- DenseNet121 — dense skip-connectivity (every layer receives every prior
  layer's feature maps); a different topology than residual addition,
  exercising a distinct path through the knowledgematrix wrapper. Note we
  use 121 (NOT 201) for compute-budget reasons.
- GoogLeNet (InceptionV1, NOT V3) — multi-branch inception modules; also the
  canonical model for the published Distill / Circuits / OpenAI Microscope
  catalogue of named neurons (e.g. Olah et al. 2017, Cammarata et al. 2020),
  which lets DeepDream channel selection cite documented features rather
  than rely on Grad-CAM picking.

All downstream code iterates over ``TIER_A_MODELS``; per-architecture
specifics (KM factory, Grad-CAM target layer, DeepDream layer schedule,
neuron-selection method) live in their respective modules' dispatch dicts.

Note: AlexNet and VGG11 (the previous TIER_A_MODELS) have been removed for
Pillar 3; their results live in ``results/km-feature-viz-cluster/`` and are
not regenerated by this manifest.

Planned follow-ups (not yet in TIER_A_MODELS): a heavier inception model
(e.g. Inception_v3 at 299×299 input, requiring per-arch shape handling) and
a transformer baseline (e.g. ViT-B/16) once the knowledgematrix wrapper for
attention blocks lands.
"""
import hashlib
import json
import os
import random
from dataclasses import dataclass
from pathlib import Path
from typing import List, Mapping, Tuple, Union

# Class IDs — ImageNet1k label indices.
#   207 = golden retriever, 282 = tiger cat, 340 = zebra
TIER_A_CLASSES = [207, 282, 340]

# Per-class image count for Pillar 3 (sums to 20).
# Retriever gets +1 (7 vs 6) to fill the headline figure's 4×2 main-text grid;
# tiger cat matches retriever at 7; zebra rounds out at 6 in the appendix.
TIER_A_IMAGES_PER_CLASS: Mapping[int, int] = {207: 7, 282: 7, 340: 6}

# Seed bumped 2026-04-26 because the class set + per-class counts changed; the
# old seed (20260421) is associated with the previous 10-class × 50-image
# manifest and must not be re-used.
TIER_A_SEED = 20260426

# Three-architecture Pillar 3 launch: residual / dense / inception family
# coverage. All three accept (3, 224, 224) inputs and produce 1000-class
# logits, so no per-arch shape branching is needed here. All downstream
# code iterates over this list — adding a new arch is a single-line append
# plus an entry in each per-arch dispatch dict (KM_MODEL_FACTORIES,
# TV_MODEL_FACTORIES, GRADCAM_TARGET_LAYERS, DEEPDREAM_LAYER_NAMES, ...).
TIER_A_MODELS = ["resnet152", "densenet121", "googlenet"]

NIBI_IMAGENET_ROOT = "/datashare/imagenet/ILSVRC2012"


@dataclass(frozen=True)
class Entry:
    model: str
    class_id: int
    image_id: str
    image_path: Path


def sample_key(entry: Entry) -> str:
    """Stable identifier used as both state key and filename stem."""
    return f"{entry.model}/{entry.class_id}/{entry.image_id}"


def _load_paths_and_labels(imagenet_root: Path) -> Tuple[List[str], List[int]]:
    """Use the repo's existing imagenet val loader; return (image_paths, labels).

    Auto-detects ImageFolder (synset subdirs) vs flat (ILSVRC2012_val_*.JPEG +
    ground-truth file) — same as `utils.utils.get_imagenet_val_dataset`."""
    from utils.utils import get_imagenet_val_dataset
    _, val_set = get_imagenet_val_dataset(str(imagenet_root))
    if hasattr(val_set, "image_paths"):
        # ImageNetVal (flat format)
        paths = list(val_set.image_paths)
        labels = list(val_set.labels)
    else:
        # torchvision.datasets.ImageFolder (synset subdirs)
        paths = [s[0] for s in val_set.samples]
        labels = [s[1] for s in val_set.samples]
    return paths, labels


def _resolve_count(images_per_class: Union[int, Mapping[int, int]], class_id: int) -> int:
    """Resolve the per-class image count from either a uniform int or a per-class mapping.

    - int: uniform count across all classes (legacy form, kept for backwards compat).
    - Mapping[int, int]: per-class count; raises KeyError with a helpful message
      if a class is not in the mapping (caller must enumerate explicitly).
    """
    if isinstance(images_per_class, int):
        return images_per_class
    if isinstance(images_per_class, Mapping):
        if class_id not in images_per_class:
            raise KeyError(
                f"images_per_class mapping missing entry for class {class_id}; "
                f"keys present: {sorted(images_per_class.keys())}"
            )
        return int(images_per_class[class_id])
    raise TypeError(
        f"images_per_class must be int or Mapping[int, int], "
        f"got {type(images_per_class).__name__}"
    )


def enumerate_entries(
    imagenet_val_dir: Path,
    classes: List[int],
    images_per_class: Union[int, Mapping[int, int]],
    seed: int,
    models: List[str],
) -> List[Entry]:
    """Build the manifest by selecting `images_per_class` images per class
    deterministically given the seed, and crossing with the model list.

    `imagenet_val_dir` is the BASE imagenet path (e.g.,
    `/datashare/imagenet/ILSVRC2012`), not the val subdir directly — matches
    the convention used by other experiments in this repo.

    `images_per_class` accepts either:
      - an ``int``: uniform count across every class (legacy form);
      - a ``Mapping[int, int]``: per-class count keyed by class_id. Every class
        in ``classes`` must have an entry.
    """
    entries: List[Entry] = []
    paths, labels = _load_paths_and_labels(imagenet_val_dir)

    # Group image paths by class label (0–999, matching ImageNet class indices).
    by_class: dict = {}
    for path, label in zip(paths, labels):
        by_class.setdefault(int(label), []).append(path)
    for c in by_class:
        by_class[c].sort()  # deterministic ordering before sampling

    rng = random.Random(seed)
    for class_id in classes:
        n_requested = _resolve_count(images_per_class, class_id)
        class_paths = by_class.get(class_id, [])
        if len(class_paths) < n_requested:
            raise ValueError(
                f"Class {class_id}: requested {n_requested} images, "
                f"only {len(class_paths)} present (base={imagenet_val_dir})"
            )
        chosen = rng.sample(class_paths, n_requested)
        for path in chosen:
            image_path = Path(path)
            image_id = image_path.stem
            for model in models:
                entries.append(
                    Entry(
                        model=model,
                        class_id=class_id,
                        image_id=image_id,
                        image_path=image_path,
                    )
                )
    return entries


def write_manifest(path: Path, entries: List[Entry]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = [
        {
            "model": e.model,
            "class_id": e.class_id,
            "image_id": e.image_id,
            "image_path": str(e.image_path),
        }
        for e in entries
    ]
    with path.open("w") as f:
        json.dump({"hash": manifest_hash(entries), "entries": payload}, f, indent=2)


def read_manifest(path: Path) -> List[Entry]:
    with path.open() as f:
        data = json.load(f)
    return [
        Entry(
            model=d["model"],
            class_id=d["class_id"],
            image_id=d["image_id"],
            image_path=Path(d["image_path"]),
        )
        for d in data["entries"]
    ]


def manifest_hash(entries: List[Entry]) -> str:
    """SHA256 over the sorted (model, class_id, image_id) triples — order-invariant."""
    triples = sorted((e.model, e.class_id, e.image_id) for e in entries)
    blob = json.dumps(triples).encode()
    return hashlib.sha256(blob).hexdigest()
